backend/models/News.php
<?php


namespace app\models;

use yii\db\ActiveRecord;
use yii\behaviors\TimestampBehavior;

use yii\helpers\ArrayHelper;
use yii\web\UploadedFile;
use common\models\User;
use Yii;

/**
 * This is the model class for table "news".
 *
 * @property int $id
 * @property int $id_user
 * @property string $title
 * @property string $body
 * @property string $created_at
 * @property string $updated_at
 * @property int $status
 * @property int $number_files
 * @property string $image
 *
 * @property File[] $files
 * @property User $user
 */
class News extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public $downFiles;
    public $imageFile;
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
                ],
                'value' => date('Y-m-d H:i:s'),
            ],
        ];
    }


    public static function tableName()
    {
        return 'news';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_user', 'status', 'number_files'], 'integer'],
            [['title', 'body', 'image'], 'string','max' => 255],
            [['body'], 'string','max' => 2555],
            [['title','body'], 'required'],
            [['imageFile'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg'],
            [['downFiles'], 'file', 'skipOnEmpty' => true, 'extensions' => 'pdf, zip, doc, docx', 'maxFiles' => 0,'maxSize'=>1024 * 1024 * 4],
            [['id_user'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['id_user' => 'id']],

        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Заголовок статьи',
            'body' => 'Текст',
            'created_at' => 'Дата создания',
            'updated_at' => 'Дата последнего обновления',
            'status' => 'Статус ',
            'number_files' => 'Кол-во прикрепленных файлов',
            'image' => 'Изображения ',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFiles()
    {
        return $this->hasMany(File::className(), ['id_news' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'id_user']);
    }

    public function upload()
    {
        $dir = Yii::getAlias('@frontend').'/web/uploads/';

        if ($this->validate()) {

            foreach ($this->downFiles as $file) {
                $file->saveAs($dir.$file->baseName . '.' . $file->extension);
            }
            return true;
        } else {
            return false;
        }
    }

    public function upload_img()
    {
        $dir = Yii::getAlias('@frontend').'/web/uploads/';
        if( $this->imageFile){
            $this->imageFile->saveAs($dir. $this->imageFile->baseName . '.' . $this->imageFile->extension);
        }
    }

    public function getImagesLinksData(){
        return ArrayHelper::toArray($this->files,[
                File::className()=>[
                'caption' => 'name_file',
                'key' => 'id'
            ]]
        );
    }
}

backend/controllers/NewsController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\AccessControl;
use common\models\LoginForm;
use yii\web\UploadedFile;
use app\models\News;
use yii\web\NotFoundHttpException;
use app\models\NewsSearch;
use app\models\File;

class NewsController extends Controller
{
    public $file_download;


    public function actionFileAjax()
    {
        if(Yii::$app->request->isAjax){

            return 11111111;
        }

        return 22222222;
    }

    public function actionPublish($id){
        $model = $this->findModel($id);
        $model->status = '1';
        $model->save();
        return $this->redirect(['index']);
    }

    public function actionFromPublication($id){
        $model = $this->findModel($id);
        $model->status = '0';
        $model->save();
        return $this->redirect(['index']);
    }

    public function actionDeleteAjax()
    {
        $dir = Yii::getAlias(   '@frontend').'/web/uploads/';

        if(Yii::$app->request->isAjax){
            $model= File::findOne((Yii::$app->request->post('key')));
            $model_news = News::findOne($model->id_news);
            $model_news->number_files = --$model_news->number_files;
            $model_news->save();
            return $model->delete();
        }

        return false;
    }



    public function actionView($id)
    {     $model_file = File::find()
        ->where(['id_news' => $id])
        ->all();
        return $this->render('view', [
            'model' => $this->findModel($id),
            'model_file' => $model_file,
        ]);
    }

    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionIndex()
    {
        $searchModel = new NewsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $model = new News();
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
          ]);
    }

    public function actionUpdateNews($id)
    {
        $model = News::findOne($id);
        $model_file = File::find()
            ->where(['id_news' => $id])
            ->all();

        if ($model->load(Yii::$app->request->post())) {
            $model->downFiles = UploadedFile::getInstances($model, 'downFiles');
            $model->imageFile = UploadedFile::getInstance($model, 'imageFile');

            if($model->imageFile){
                $model->image = $model->imageFile->name;
            }
            $model->number_files += count($model->downFiles);
            $model->save();
            $model->upload();
            $model->upload_img();
            $this->saveGalaryItems($model->downFiles,$model->id);

            Yii::$app->session->setFlash('success','Your article update '.$model->title.' !!!!');
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('updateNews', [
            'model' => $model,
            'model_file'=>$model_file
        ]);
    }


    public function actionCreateNews()
    {
        $model = new News();
        if($model->load(Yii::$app->request->post())){

            $model->downFiles = UploadedFile::getInstances($model, 'downFiles');
            $model->imageFile = UploadedFile::getInstance($model, 'imageFile');
           // print_r( $model->imageFile->name);return;
            $model->status = '0';
            $model->id_user = $_SESSION['__id'];
            $model->number_files = count($model->downFiles);
            $model->image = $model->imageFile->name;

            $model->save();
            $model->upload();
            $model->upload_img();
            $this->saveGalaryItems($model->downFiles,$model->id);

            Yii::$app->session->setFlash('success','Your article save '.$model->title.' !!!!');

            return $this->redirect(['/news']);
        }else {
            return $this->render('createNews', [
                'model' => $model,
            ]);
        }

    }


    protected function saveGalaryItems($items,$news_Id)
    {
        foreach ($items as $tems_galary)
        {
            $gallery_items = new File();
            $gallery_items->id_news = $news_Id;
            $gallery_items->name_file = $tems_galary->name;
            $gallery_items->save();
        }
    }

    protected function findModel($id)
    {
        if (($model = News::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/views/news/createNews.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;
use kartik\file\FileInput;
use dosamigos\ckeditor\CKEditor;
use yii\helpers\Url;

$this->title = 'News';
$this->params['breadcrumbs'][] = $this->title;


?>

<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
    </p>

    <div class="row">
        <div class="col-lg-9">
            <?php $form = ActiveForm::begin(['id' => 'contact-form', 'options' =>['enctype'=>'multipart/form-data']]); ?>

            <?= $form->field($model, 'title')->textInput(['autofocus' => true]) ?>

            <?= $form->field($model, 'body')->widget(CKEditor::className(), [
                'options' => ['rows' => 6],
                'preset' => 'basic'
            ]) ?>

            <?= $form->field($model, 'imageFile')->widget(FileInput::classname(), [
                'name' => 'input-ru[]',
                'language' => 'ru',
                'options' => ['accept' => 'pdf, zip, doc, docx','multiple' => true],
                'pluginOptions' => ['previewFileType' => 'any']
            ]);
            ?>

            <?= $form->field($model, 'downFiles[]')->widget(FileInput::classname(), [
                'name' => 'input-ru[]',
                'language' => 'ru',
                'options' => ['accept' => 'pdf, zip, doc, docx','multiple' => true],
                'pluginOptions' => ['previewFileType' => 'any']
            ]);
            ?>

            <div class="form-group">
                <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>

</div>

backend/views/news/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use yii\bootstrap\ButtonDropdown;
/* @var $this yii\web\View */
/* @var $searchModel app\models\NewsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'News';
$this->params['breadcrumbs'][] = $this->title;
/*echo "<pre>";
print_r($model);
echo "</pre>";*/
?>
<div class="news-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create News', ['create-news'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'title',
            'created_at',
            'updated_at',
            [   'attribute' => 'status',
                'format' => 'raw',
                'filter' => [
                    1 => 'Активен',
                    0 => 'Завершен',
                ],
                'value' => function ($data) {
                    $status = $data->status;
                    return $status ? '<span class =\'label label-success\'>Опубликован</span>':'<span class =\'label label-danger\'>Не опубликован</span>';
                },
            ],
            //'status',
            //'number_files',
            [   'attribute' => 'number_files',
                'format' => 'raw',
                'filter' => [
                    2 => '2',
                    3 => '3',
                    4 => '4',
                    5 => '5',
                    6 => '6',
                    9 => '9',
                    15 => '15',
                    20 => '20',
                ],
            ],
            //'image',
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{view} {delete} {update-news} {all}',
                'buttons' => [
                    'update-news' => function ($url, $model, $key) {
                        return Html::a('<span class="	glyphicon glyphicon-pencil">',
                            ['update-news', 'id'=>$model->id]);
                    },
                    'all' => function ($url, $model, $key) {
                        return ButtonDropdown::widget([
                            'encodeLabel' => false,
                            'label' => 'Статус',
                            'dropdown' => [
                                'encodeLabels' => false,
                                'items' => [
                                    [
                                        'label' => \Yii::t('yii', 'Опубликовать'),
                                        'url' => ['publish', 'id' => $key],
                                    ],
                                    [
                                        'label' => \Yii::t('yii', 'С публикации'),
                                        'url' => ['from-publication', 'id' => $key],
                                        'visible' => true,
                                    ],
                                ],
                                'options' => [
                                    'class' => 'dropdown-menu-right',
                                ],
                            ],
                            'options' => [
                                'class' => 'btn-default',
                            ],
                            'split' => false,
                        ]);
                    },
                ],
            ],
        ],
    ]); ?>
</div>

backend/views/news/updateNews.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;
use kartik\file\FileInput;
use dosamigos\ckeditor\CKEditor;
use yii\helpers\Url;

$this->title = 'News';
$this->params['breadcrumbs'][] = $this->title;

for($i=0;$i<count($model_file);$i++){
    $html_img[$i] = "<img src='/uploads/".$model_file[$i]['name_file']."' alt title='2342341' style='width: 210px'>";
    $html_title[$i] =  ['caption' => $model_file[$i]['name_file'],'key'=>$model_file[$i]['id']];
}

?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>
    <div class="row">
        <div class="col-lg-9">
            <?php $form = ActiveForm::begin(['id' => 'contact-form', 'options' =>['enctype'=>'multipart/form-data']]); ?>

            <?= $form->field($model, 'title')->textInput(['autofocus' => true]) ?>

            <?= $form->field($model, 'body')->widget(CKEditor::className(), [
                'options' => ['rows' => 6],
                'preset' => 'basic'
            ]) ?>

            <?= $form->field($model, 'status')->checkbox([
                'label'=>'Снять с публикации/опубликовать',
                'data-toggle'=>'toggle'
            ]) ?>

            <?= $form->field($model, 'imageFile')->widget(FileInput::classname(), [
                'name' => 'input-ru[]',
                'language' => 'ru',
                'options' => ['accept' => 'png, jpg , gif','multiple' => true ],
                'pluginOptions' => [
                    'initialPreview'=>[
                        Html::img("/uploads/" . $model->image,['class' => 'imagg'])
                    ],

                    'overwriteInitial'=>true,
                    'previewFileType' => 'any',
                    'uploadUrl' => Url::to(['/site/file-upload']),


                ],
            ]);
            ?>

            <?= $form->field($model, 'downFiles[]')->widget(FileInput::classname(), [
                'name' => 'input-ru[]',
                'options' => ['accept' => 'pdf, zip, doc, docx','multiple' => true],
                'pluginOptions' => [
                    'deleteUrl' => Url::toRoute(['/news/delete-ajax']),
                    'initialPreview'=>$html_img,
                    'initialPreviewAsData'=>true,
                    'overwriteInitial'=>false,
                    'initialPreviewConfig'=> $model->getImagesLinksData(),
                    'uploadUrl' => Url::to(['/news/file-ajax']),
                    'previewFileType' => 'any'
                ],
            ]);
            ?>




            <div class="form-group">
                <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>

</div>

backend/views/news/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $model app\models\News */
$dir = Yii::getAlias('@frontend').'/uploads/';
$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'News', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="news-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update-news', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

        <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'title',
            'body',
            'created_at',
            'updated_at',
            [   'attribute' => 'status',
                'format' => 'raw',
                'filter' => [
                    1 => 'Опубликован',
                    0 => 'Не опубликован',
                ],
                'value' => function ($data) {
                    $status = $data->status;
                    return $status ? '<span class =\'label label-success\'>Опубликован</span>':'<span class =\'label label-danger\'>Не опубликован</span>';
                },
            ],
            [
                'attribute'=>'image',
                'value'=> '/uploads/'.$model->image,
                'format' => ['image',['width'=>'30%']],
            ],
        ],
    ]) ?>

</div>
<div>
    <div class="container">
        <ul class="list-group">
            <li class="list-group-item active"> Кол-во прикрепленных файлов</li>
            <?php foreach($model_file as $item):?>
                <li class="list-group-item"><?=$item->name_file?> </li>
            <?php endforeach;?>
            </ul>
    </div>
</div>